-- 코드를 입력하세요
SELECT  YEAR(O.SALES_DATE) AS YEAR, 
        MONTH(O.SALES_DATE) AS MONTH, 
        U.GENDER AS GENDER,
        COUNT(DISTINCT O.USER_ID) USERS
        FROM ONLINE_SALE O
JOIN USER_INFO U
    ON U.USER_ID = O.USER_ID
WHERE U.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;